name: CI

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Execute tests.bat
      run: |
        .\project\tests.bat
    
    - name: Set Git identity
      run: |
        git config --global user.email "vaishnavnegi207@gmail.com"
        git config --global user.name "vaishnavnegi"

    - name: Commit and Push CSV files
      run: |
        echo Adding CSVs to data directory.
        git add data\it20.csv
        git add data\ipl.csv

        git commit -m "Add generated CSV files" -a
        git push origin main

