name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Execute tests.sh
      run: |
        chmod +x ./tests.sh
        ./tests.sh

    - name: Save DataFrame to Pickle file
      run: |
        python3 /path/to/Project/df_to_pickle.py  
